const SAVE_TASK_TO_STORE = 'SAVE_TASK_TO_STORE'
const SAVE_TASK_TO_STORE_SUCCESS = 'SAVE_TASK_TO_STORE_SUCCESS'
const SAVE_DONE_TASK_TO_STORE = 'SAVE_DONE_TASK_TO_STORE'
const SAVE_LATE_TASK_TO_STORE = 'SAVE_LATE_TASK_TO_STORE'
const LOGIN_REQUEST = 'LOGIN_REQUEST';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILURE = 'LOGIN_FAILURE';
const LOGOUT = 'LOGIN';
const REGISTRATION = 'REGISTRATION';

export {
    SAVE_TASK_TO_STORE,
    LOGIN_REQUEST,
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    LOGOUT,
    REGISTRATION,
    SAVE_DONE_TASK_TO_STORE,
    SAVE_LATE_TASK_TO_STORE,
    SAVE_TASK_TO_STORE_SUCCESS,
}